# Generated by Django 4.2.29 on 2026-03-22 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True)),
                ('actor_email', models.EmailField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], max_length=10, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('OPERATOR', 'Operator'), ('ADMIN', 'Admin')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.user')),
            ],
            bases=('records.user',),
        ),
        migrations.CreateModel(
            name='SprayRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_email', models.EmailField(db_index=True, max_length=255)),
                ('date_applied', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('pcp_act_number', models.CharField(max_length=64)),
                ('chemical_volume_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_volume_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry_polygon', models.JSONField(blank=True, null=True)),
                ('geometry_center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('geometry_center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged')], db_index=True, default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spray_records',
                'indexes': [models.Index(fields=['date_applied'], name='idx_date'), models.Index(fields=['product_name'], name='idx_product'), models.Index(fields=['pcp_act_number'], name='idx_pcp')],
            },
        ),
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('records.user',),
        ),
    ]
