"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

This file configures our entire project. It tells Django: 
    - What database to use, which in our case is MySQL matching the schema you provided 
    - What apps are installed (our 'records' app where we define the models and views)
    - How to handle security and what not 

The Environment variables are loaded from a .env file, so passwords and keys are never hardcoded. 
To differentitate between what was auto-generated and what was added by us, I have added comments in the code.
"""
import os                   #Added
from pathlib import Path
from dotenv import load_dotenv #Added

#To load the environment variables from the .env file we do.... 
load_dotenv() #Added

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# We want to keep this secret key out of our code, so we load it from an environment variable.
SECRET_KEY = os.environ.get ("DJANGO_SECRET_KEY", "backup-secret-key-for-development-only") #Altered to load from .env 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") #Altered to load from .env and split into a list


# Application definition
# First 6 are the built in Django apps, and the last one is our app 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'records', #This is where we define our models and views for the patterns. 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# This is the section that connects Django to our database you guys set up. 
# To increase security I made everything come from the .env file. 
# As a check here our database name is "spray_records"
# This Databases section is altered from what was generated by Django. 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'spray_records'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        #The options section here is telling mysql to be strict with the data and runs on initialization. I have seen in videos this helps with preventing bad data. 
        'OPTIONS': { 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'" }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ADDED SECTIONS BELOW THIS LINE
#########################################################################

# Google Maps Key 
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Logging Config 
# This is just logging config stuff that will write logs to a console and a file. This will works along with the observer pattern
# I think its implemented correctly, I got the info from the Djangoproject website logging pages. 
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True) # Make sure the logs directory exists

LOGGING = { 
    "version": 1,
    "disable_existing_loggers": False,
    
    #Format control what our log messages will look like. This will provide a timestamp, log level, logger name, and the message.
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },

    #Handlers control where the messages will go, we want a file and the console. 
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "app.log",
            "formatter": "verbose",
        },
    },

    #Loggers section 
    # IN our files we will use logging.getLogger("records")
    # This will connect to the logger defined here and send the messages to both the console and the file.
    "loggers": {

        #This is used in the views.py and factory.py for just general messages 
        # Used for record created or updated, things like that.
        "records": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },

        #Observer is in the observer.py for any observer messages 
        #I think this is like observers being registered, or notifying observers, things like that.
        "observer": {
            "handlers": ["console", "file"],
            "level": "INFO",
        },
    },
}
